<html>
    <head>
        <meta charset="utf-8" />
        <title>Ma page de passagers</title>
    </head>
    <body>
        <h1>CONFIRMATION DES RESERVATIONS</h1></br></br></br>
        <p>Votre demande a été bien enregistrée.</p></br>
        <p>Merci de bien vouloir verser la somme de <?php echo $prix; ?> euros sur le compte 000-000000-00</p>
        <form action ="index.PHP?page=accueil">
            <input type ="submit" value ="Retour à la page précédente" />
        </form>
    </body>
</html>